# tipos numericos float e int
print(dir(int))
print('')
print(dir(float))
print('')
print('')
print('')
print('')
a = 5
b = 2.5
print(a / b)
print(a + b)
print(a * b)
print('')
print(type(a))
print(type(b))
print(type(a - b))
print(b.is_integer())
print(5.0.is_integer())
print('')
print(dir(int))
print('')
print(int.__add__(2,3))
print((-2).__abs__())
print(abs(-2))
print(abs(-3.6))