print('Tipos Booleans')
print(True)
print(False)
print('')
print('float e inteiro')
print(1.2 + 1)
print('')
print('no print tenho a possibilidade de escrever qualquer texto: aushaushausha')
print("Aspas duplas funciona muito bem aqui tambem!")
print("Mistura de tipos: Voce e" + 3 * " muito " + "legal! (contatenacao)")
# print(3 + '3') -> ambiguidade. Python não advinha o que você quer fazer! (zen of python)
print('')
print('lista')
print([1,2,3,4,5,6])
print('')
print('chave-valor dicionario')
print({'nome': 'thiago', 'idade': '23'})
print('')
print('Ausencia de valor')
print(None)

