tupla = tuple()
print(type(tupla))
print(dir(tupla))
#print(help(tupla))
tupla = ('um')
print(type(tupla))
tupla = ('um',)
print(type(tupla))
print(tupla[0])
cores = ('verde', 'amarelo', 'azul', 'branco')
print(cores)
print(cores[1])
print(cores[-1])
print(cores[1:])
print(cores.index('amarelo'))
print(cores.count('azul'))
print(cores.count('roxo'))
print(len(cores))